name: Java CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        jvmversion: [1.8, 11, 17]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK ${{matrix.jvmversion}}
      uses: actions/setup-java@v1
      with:
        java-version: JDK ${{matrix.jvmversion}}
    - name: Build with Gradle
      run: ./gradlew build
