name: Java CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        jvmversion: [8, 11]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '${{matrix.jvmversion}}'
      - name: Build with Gradle
        run: ./gradlew build
