name: Build CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        jvmversion: [8, 11, 17, 21]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${{matrix.jvmversion}}'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
